### ISSUE TITLE
proxmox inventory : be able to selectively disable compose for proxmox nodes

### ISSUE THREAD

**Issue by GuillaumeV-cemea** [ansible-collections/community.proxmox#54]
### Summary

Since version 7.1 (specifically, PR ansible-collections/community.general#6641), you can now use compose var for proxmox nodes. My issue is that in my compose vars, I'm using some `proxmox_*` (defined by the inventory plugin) var as a base, something like this : 
```
want_facts: true
compose:
  host_shortname: proxmox_hostname | default(proxmox_name)
```

However, since version 7.1, the inventory plugin tries to create compose var for proxmox nodes, but in my case it fails because neither `proxmox_hostname` nor `proxmox_name` (or any `proxmox_*` vars) are defined for proxmox node.

It seems to me that compose vars are mostly used with `proxmox_*` vars (this is the example for compose vars in the documentation), which wouldn't work for proxmox nodes.

If I want to use `proxmox_*` vars in my compose vars, I see 4 options : 

* Use `strict: false` in my inventory, so it  will silently fail for proxmox node and work for everything else. I don't like this, because `strict: true` is a good way to check for error in my inventory (I catched many bugs in my code with this)
* Don't use `proxmox_*` vars, not really an option IMO
* Use `| default` in my code to provide default value for all non-defined proxmox variables. It could work, but it'll uglify the code quite a bit
* Be able to disable compose vars for proxmox_node (with a default set to enable them, since this is the behaviour since 7.1)

Do you think the last option would be a good idea ? It seems like my use case is a relatively common one and this could benefit others. I can make a PR if you want :)

### Issue Type

Feature Idea

### Component Name

proxmox inventory

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by PendaGTP** [comment]
I'm unable to reproduce this issue, I think this is resolved.

**Comment by GuillaumeV-cemea** [comment]
This is still happening for me. I tried on two proxmox nodes : one on 8.3.3, one on 9.1.6. I've removed all my host_vars/group_vars for this test and kept only the proxmox inventory file.
Here is the inventory.courgette.proxmox.yml I'm using : 
```
plugin: community.proxmox.proxmox
cache: false
url: https://redacted.fr:8006
user: "{{ lookup('community.general.bitwarden', 'redacted', search='id', field='username')[0] }}"
password: "{{ lookup('community.general.bitwarden', 'redacted', search='id', field='password')[0] }}"
want_proxmox_nodes_ansible_host: true
want_facts: true
strict: true
compose:
  host_shortname: proxmox_hostname | default(proxmox_name)
```

Ansible version, and collection version : 
```
(venv) GuillaumeV@83-23014-mint:~/code/ansible-cemea$ ansible --version
ansible [core 2.18.3]
  config file = /home/GuillaumeV/code/ansible-cemea/ansible.cfg
  configured module search path = ['/home/GuillaumeV/code/ansible-cemea/modules']
  ansible python module location = /home/GuillaumeV/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/GuillaumeV/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/GuillaumeV/.local/bin/ansible
  python version = 3.12.3 (main, Mar  3 2026, 12:15:18) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
(venv) GuillaumeV@83-23014-mint:~/code/ansible-cemea$ ansible-galaxy collection list

# /home/GuillaumeV/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.posix                            2.1.0  
community.crypto                         3.0.1  
community.dns                            3.2.1  
community.docker                         3.3.2  
community.general                        10.4.0 
community.grafana                        2.3.0  
community.library_inventory_filtering_v1 1.1.1  
community.proxmox                        1.6.0  
grafana.grafana                          6.0.6  
prometheus.prometheus                    0.27.5 
```
Here is the output of ansible-inventory on host courgette (my proxmox node name) : 
```
(venv) GuillaumeV@83-23014-mint:~/code/ansible-cemea$ ansible-inventory -vvvvv -i inventory/courgette.proxmox.yml --host courgette
ansible-inventory [core 2.18.3]
  config file = /home/GuillaumeV/code/ansible-cemea/ansible.cfg
  configured module search path = ['/home/GuillaumeV/code/ansible-cemea/modules']
  ansible python module location = /home/GuillaumeV/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/GuillaumeV/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/GuillaumeV/.local/bin/ansible-inventory
  python version = 3.12.3 (main, Mar  3 2026, 12:15:18) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
Using /home/GuillaumeV/code/ansible-cemea/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from 
host_list declined parsing /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml as it did not pass its verify_file() method
script declined parsing /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml as it did not pass its verify_file() method
Loading collection community.proxmox from /home/GuillaumeV/.ansible/collections/ansible_collections/community/proxmox
Using inventory plugin 'ansible_collections.community.proxmox.plugins.inventory.proxmox' to process inventory source '/home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml'
Loading collection community.general from /home/GuillaumeV/.ansible/collections/ansible_collections/community/general
Interface eno2 on node courgette does not have an address
Interface enp5s0f1 on node courgette does not have an active state
Interface enxa2dd4f1dcc02 on node courgette does not have an active state
Interface eth0 on node courgette does not have an address
Using interface vmbr0 on node courgette with addressredacted.redacted.redacted.redacted as node ip for ansible_host
toml declined parsing /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml with auto plugin: Could not set host_shortname for host courgette: 'proxmox_name' is
undefined
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/inventory/manager.py", line 292, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/home/GuillaumeV/.ansible/collections/ansible_collections/community/proxmox/plugins/inventory/proxmox.py", line 724, in parse
    self._populate()
  File "/home/GuillaumeV/.ansible/collections/ansible_collections/community/proxmox/plugins/inventory/proxmox.py", line 669, in _populate
    self._set_composite_vars(self.get_option("compose"), variables, node["node"], strict=self.strict)
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/plugins/inventory/__init__.py", line 359, in _set_composite_vars
    raise AnsibleError("Could not set %s for host %s: %s" % (varname, host, to_native(e)))
[WARNING]:  * Failed to parse /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/inventory/manager.py", line 292, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/plugins/inventory/yaml.py", line 113, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/inventory/manager.py", line 292, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/GuillaumeV/.local/lib/python3.12/site-packages/ansible/plugins/inventory/ini.py", line 137, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /home/GuillaumeV/code/ansible-cemea/inventory/courgette.proxmox.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "ansible_host": "redacted IP"
}
```

**Comment by PendaGTP** [comment]
Thanks for your reply! I have miss something..

**Comment by PendaGTP** [comment]
Having a global option `compose_proxmox_nodes` to enable/disable compose is ok or you need to enable/disable by host? Any idea of what the configuration might looks like?

**Comment by GuillaumeV-cemea** [comment]
For this issue, I don't see a point of disabling compose for anything other than a proxmox_node, but maybe a more general option which allow to disable compose for any machine could be useful - but then, how would you specify which machine to compose ? 
Imo a global option `want_proxmox_nodes_compose_vars` (let's keep the naming consistent with other variables) is what is needed
